### ISSUE TITLE
Eclipse Plugin doesn't work

### ISSUE THREAD

**Issue by adeptues** [mdht/mdht#156]
The eclipse plugin for modelling new CDA documents do not work. it fails to start when choosing new CDA model from the wizard selection there is an error 

```
unable to create CDA Project, No Available CDA Documents in Workspace!
```

Except there are no up to date instructions on how to add them to the workspace and any instructions that do exist are out of date and do not work.

How can i resolve this?

**Comment by swmuir** [comment]
Here is the installer for MDHT https://github.com/mdht/mdht-models/tree/develop/releng/setups
Use the MDHT Modeler 

Are you looking to model CDA Implementation guides ?  Most people are looking for the java api

The error you are receiveing is the CDA model and dependenent models currently needs to be in the  workspace

**Comment by adeptues** [comment]
Thanks for that link i've got eclipse to work now. I'm probably looking to do both, is there a guide for the java api aswell? specifically i'll be using org.hl7.cbcc.privacy.consentdirective

**Comment by swmuir** [comment]
We have those modeled - i think the runtime is in MDHT models 


so no need to model the IG 

there is some basic documentation here 

http://www.cdatools.com/docs/developeruserguide/org.openhealthtools.mdht.cda.doc.developerguide/topics/topic_Developers_Guide.html

**Comment by adeptues** [comment]
Thanks, think i've figured out what to do.

Have you got any javadocs for the API i tried to generate them via maven from the mdht-models project in github but it failed

EDIT - ignore that i've sorted it

**Comment by adeptues** [comment]
After downloading the java api from https://github.com/mdht/mdht-models/releases and adding the jars to the project it now results in 

```
java.lang.ClassNotFoundException: org.eclipse.uml2.types.TypesPackage
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1907)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1750)
	at org.eclipse.mdht.uml.hl7.datatypes.impl.DatatypesPackageImpl.init(DatatypesPackageImpl.java:440)
	at org.eclipse.mdht.uml.hl7.datatypes.DatatypesPackage.<clinit>(DatatypesPackage.java:66)
	at org.eclipse.mdht.uml.hl7.rim.impl.RIMPackageImpl.init(RIMPackageImpl.java:138)
	at org.eclipse.mdht.uml.hl7.rim.RIMPackage.<clinit>(RIMPackage.java:62)
	at org.eclipse.mdht.uml.cda.impl.CDAPackageImpl.init(CDAPackageImpl.java:763)
	at org.eclipse.mdht.uml.cda.CDAPackage.<clinit>(CDAPackage.java:66)
	at org.hl7.cbcc.privacy.consentdirective.impl.CONSENTDIRECTIVEPackageImpl.init(CONSENTDIRECTIVEPackageImpl.java:261)
	at org.hl7.cbcc.privacy.consentdirective.CONSENTDIRECTIVEPackage.<clinit>(CONSENTDIRECTIVEPackage.java:56)
	at org.hl7.cbcc.privacy.consentdirective.CONSENTDIRECTIVEPackage$Literals.<clinit>(CONSENTDIRECTIVEPackage.java:5274)
	at org.hl7.cbcc.privacy.consentdirective.impl.PrivacyConsentDirectiveDocumentImpl.eStaticClass(PrivacyConsentDirectiveDocumentImpl.java:44)
	at org.eclipse.emf.ecore.impl.EObjectImpl.eClass(EObjectImpl.java:263)
	at org.eclipse.mdht.emf.runtime.util.Initializer$Util.init(Initializer.java:442)
	at org.hl7.cbcc.privacy.consentdirective.impl.PrivacyConsentDirectiveDocumentImpl.init(PrivacyConsentDirectiveDocumentImpl.java:241)
```

This is after adding all the jars from the releases page and getting the latest UML2 types jar from maven/eclipse

Any idea's? i mean it obviously suggests its not on the class path but the UML2 types jar is

**Comment by swmuir** [comment]
Which specific release did you select ? 
sean

**Comment by adeptues** [comment]
The latest one MDHT_CCDA_R2.1_R1.1_MU2_DS4P_20180531_build.zip

https://github.com/mdht/mdht-models/releases/tag/v3.0.8.20180531_Consol2

EDIT --
I've fixed the problem temporarily by adding all the jars directly to tomcat libs folder so their picked up by the tomcat classloader. However this approach isn't suitable for production as they need adding to the maven pom which is difficult as they some of the jars have dependencies on the other non mdht jars.

Is their a way to build the jars from source using maven so i can issue a maven deploy command to our internal nexus repository so they can be easily used in the future?

I've attempted to build the mdht-models project but it fails on a simple mvn package command
